// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgpqZC3CKeho9_5C9iCLJ2nVITBXJRW4',
    appId: '1:615041897431:web:57d40f0d022f095de63192',
    messagingSenderId: '615041897431',
    projectId: 'chat-app-2b5c8',
    authDomain: 'chat-app-2b5c8.firebaseapp.com',
    storageBucket: 'chat-app-2b5c8.appspot.com',
    measurementId: 'G-1BVP5FCMZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk6X8_9wa29ofDH8_Rcc6TDtvGk4ekcyQ',
    appId: '1:615041897431:android:45ccb121a2304725e63192',
    messagingSenderId: '615041897431',
    projectId: 'chat-app-2b5c8',
    storageBucket: 'chat-app-2b5c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Nwy320NayiED4fJrhzXMMGG1WCtslIA',
    appId: '1:615041897431:ios:882f81a5ff5c2673e63192',
    messagingSenderId: '615041897431',
    projectId: 'chat-app-2b5c8',
    storageBucket: 'chat-app-2b5c8.appspot.com',
    iosClientId: '615041897431-9e59hvqtmv66kmri28lv9lh5t9drnco5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Nwy320NayiED4fJrhzXMMGG1WCtslIA',
    appId: '1:615041897431:ios:882f81a5ff5c2673e63192',
    messagingSenderId: '615041897431',
    projectId: 'chat-app-2b5c8',
    storageBucket: 'chat-app-2b5c8.appspot.com',
    iosClientId: '615041897431-9e59hvqtmv66kmri28lv9lh5t9drnco5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
